spring:
  redis:
#    cluster:
#      nodes: localhost:6379 #127.0.0.1:9001,127.0.0.1:9002 #127.0.0.1:9003
#    #----------单机配置-------------------
    #host: localhost #实例的地址
    #port: 6379 #端口

    #-------------集群配置----------------
      #多个主机配置
      #nodes: 127.0.0.1:6379,127.0.0.1:9001,127.0.0.1:9002,127.0.0.1:9003

      #主机host一样

    #max-redirects: 2 #获取失败 最大定向次数


#      cluster:
#        nodes:
#          - 6379
#          - 9000
#          - 9001
#          - 9002



    host: localhost
    port: 6379
    jedis:
      pool:
        max-wait: 0 # 连接池中的最大空闲连接
        max-active: 9 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 1 # 连接池中的最小空闲连接
        min-idle: 0 #连接池最小空闲连接数


